apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  namespace: ansidev
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - name: node-port
          containerPort: 80