# permissions for end users to view ansiconfigmaps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ansiconfigmap-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: config-operator
    app.kubernetes.io/part-of: config-operator
    app.kubernetes.io/managed-by: kustomize
  name: ansiconfigmap-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - ansiconfigmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - ansiconfigmaps/status
  verbs:
  - get
