# permissions for end users to view testconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: testconfig-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: test-config
    app.kubernetes.io/part-of: test-config
    app.kubernetes.io/managed-by: kustomize
  name: testconfig-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - testconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - testconfigs/status
  verbs:
  - get
