# permissions for end users to edit mymemcacheds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mymemcached-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: my-memcahced-operator
    app.kubernetes.io/part-of: my-memcahced-operator
    app.kubernetes.io/managed-by: kustomize
  name: mymemcached-editor-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - mymemcacheds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - mymemcacheds/status
  verbs:
  - get
