# permissions for end users to edit ansidevelopments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ansidevelopment-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ansible-development-op
    app.kubernetes.io/part-of: ansible-development-op
    app.kubernetes.io/managed-by: kustomize
  name: ansidevelopment-editor-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - ansidevelopments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - ansidevelopments/status
  verbs:
  - get
