---
- name: Create the cache.example.com/v1alpha1.TestcOnfig
  k8s:
    state: present
    namespace: '{{ namespace }}'
    definition: "{{ lookup('template', '/'.join([samples_dir, cr_file])) | from_yaml }}"
    wait: yes
    wait_timeout: 300
    wait_condition:
      type: Successful
      status: "True"
  vars:
    cr_file: 'cache_v1alpha1_testconfig.yaml'

- debug: var=namespace
  vars:
    namespace: '{{lookup("kubernetes.core.k8s",apiVersion="v1",kind="Namespace")}}'  

- debug: var=service
  vars:
    service: '{{lookup("kubernetes.core.k8s",apiVersion="v1",kind="Service",namespace="test-config",my_resource="web")}}'  
