---
- name: Namespace for config is "{{ namespace }}"
  kubernetes.core.k8s:
    kind: Namespace
    api_version: v1
    state: "{{ namespace }}"
    name: testing
- name: ConfigMap Example is "{{ state }}"
  kubernetes.core.k8s:
    kind: ConfigMap
    api_version: v1
    name: example-configmap
    namespace: testing 
    state: "{{ state }}"
  ignore_errors: true
- name: service Example for Namespace
  kubernetes.core.k8s:
    kind: Service
    api_version: v1
    namespace: testing
    name: example-service
    spec:
      ports:
      - port: 80
        protocol: TCP
