- name: Create a Service object from an inline definition
  kubernetes.core.k8s:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: web
        namespace: jinja
        labels:
          app: nginx
      spec:
        selector:
          app: nginx
        ports:
        - protocol: TCP
          targetPort: node-port
          port: 8000
        type: NodePort  
      
