# permissions for end users to edit nginxhelms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nginxhelm-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: helm-operator
    app.kubernetes.io/part-of: helm-operator
    app.kubernetes.io/managed-by: kustomize
  name: nginxhelm-editor-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - nginxhelms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - nginxhelms/status
  verbs:
  - get
