# permissions for end users to view jinjasvcs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: jinjasvc-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: j2operator
    app.kubernetes.io/part-of: j2operator
    app.kubernetes.io/managed-by: kustomize
  name: jinjasvc-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - jinjasvcs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - jinjasvcs/status
  verbs:
  - get
